version: '3'

services:
  front-end:
    container_name: frond-end-js-svelte
    build: ./front-end/
    command: sh ./start.sh
    env_file: .env
    networks:
      - base
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - web-app:/front-end/public
  backend:
    container_name: backend-go-fiber
    build: backend/
    command: sh ./start.sh
    env_file: .env
    expose:
      - "4000"
    ports:
      - "4000:4000"
    networks:
      - base
    depends_on:
      - mysql-db
    volumes:
      - ./backend/:/app
  mysql-db:
    container_name: db-mysql
    restart: always
    build: mysql-db-config
    ports:
      - "3306:3306"
    networks:
      - base
    env_file: .env
    volumes:
      - ./mysql-db-data:/var/lib/mysql
  nginx:
    container_name: nginx-reverse-proxy
    restart: always
    build: nginx
    expose:
      - "80"
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - web-app:/usr/share/nginx/html
    links:
      - backend
    networks:
      - base

networks:
  base:

volumes:
  web-app: